[package]
name = "bevy_xpbd_3d"
version = "0.1.0"
edition = "2021"

[features]
default = [ "3d" ]
3d = []

[lib]
name = "bevy_xpbd_3d"
path = "../../src/lib.rs"
required-features = [ "3d" ]

[dependencies]
bevy = "0.8.0"
parry3d = { version = "0.9.0" }
nalgebra = { version = "0.31.0", features = [ "convert-glam021" ] }
console_error_panic_hook = "0.1"
web-sys = "0.3.59"

[dev-dependencies]
examples_common_3d = { path = "../examples_common_3d" }

[package.metadata.rust-analyzer.cargo]
features = ["3d"]